# Generated by Django 2.0.6 on 2018-06-24 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('displaystarttime', models.DateTimeField(blank=True, db_column='displayStartTime', null=True)),
                ('displayendtime', models.DateTimeField(blank=True, db_column='displayEndTime', null=True)),
                ('availablestarttime', models.DateTimeField(blank=True, db_column='availableStartTime', null=True)),
                ('avaliableendtime', models.DateTimeField(blank=True, db_column='avaliableEndTime', null=True)),
                ('createat', models.DateTimeField(blank=True, db_column='createAt', null=True)),
                ('courseid', models.IntegerField(blank=True, db_column='courseId', null=True)),
                ('chapters', models.ManyToManyField(to='backend.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='ExamParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(db_column='userId')),
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('examid', models.ForeignKey(db_column='examId', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('options', models.TextField(blank=True, max_length=255)),
                ('solution', models.CharField(blank=True, max_length=20)),
                ('author', models.IntegerField(blank=True, null=True)),
                ('keypoints', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('questions', models.ManyToManyField(to='backend.Question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='backend.Question'),
        ),
    ]
