# Generated by Django 2.0.6 on 2018-07-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.CharField(default='测试教师', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.TextField(blank=True),
        ),
    ]
