# Generated by Django 2.0.6 on 2018-07-01 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180701_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='createat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
