# Generated by Django 2.0.6 on 2018-07-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180701_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examparticipation',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='backend.Exam'),
        ),
        migrations.AlterField(
            model_name='examparticipation',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
